

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

fibo = 0





fibu = 1
fibo = 2
sum = 0

while fibo < 4000000:
    if fibo % 2== 0:
        sum = sum +fibo    
    temp = fibo
    fibo = fibo + fibu
    fibu = temp

print(sum)
    



    
    
    
